name: sio113-2021-python
channeks:
  - conda-forge
dependencies:
  - python=3.8
  - future=0.18.2
  - numpy=1.20.1
  - scipy=1.6.1
  - matplotlib=3.3.4
  - pandas
  - scikit-learn
  - geopandas
  - geoplot
  - cartopy


