#!/bin/bash
echo $PATH > postBuild.log
which gcc >> postBuild.log
gcc --version >> postBuild.log
which gfortran >> postBuild.log
gfortran --version >> postBuild.log
which c++ >> postBuild.log
c++ --version >> postBuild.log
